---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: prometheus-pvc
    labels:
        app: prometheus
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prometheus
    spec: 
      containers:
      - name: prometheus
        image: IMAGE
        args:
        - '--config.file=/prometheus.yml'
        - '--storage.tsdb.path=prometheus_data/'
        ports:
        - containerPort: 9090
          name: prometheus 
        resources:
            limits:
              cpu: 500m
              memory: 1Gi
        volumeMounts:
        - name: prometheus-persistent-storage
          mountPath: prometheus_data/
        - name: prometheus-config
          mountPath: /prometheus.yml
          subPath: prometheus.yml
      volumes:
      - name: prometheus-persistent-storage
        persistentVolumeClaim:
          claimName: prometheus-pvc
      - name: prometheus-config
        configMap:
          name: prometheus-config
          defaultMode: 0744